//
// Created by lambert on 23-6-2.
//

#pragma once
enum class state_code {
    SUCCESS = 0,

    REGISTRATION_NICKNAME_EXISTS = 101,
    REGISTRATION_EMAIL_EXISTS = 102,
    REGISTRATION_SERVER_ERROR = 110,

    LOGIN_ID_NOT_EXIST = 121,
    LOGIN_USERNAME_NOT_EXIST = 122,
    LOGIN_EMAIL_NOT_EXIST = 123,

    LOGIN_PASSWORD_ERROR = 131,

    REGISTRATION_CLIENT_ERROR = 151,
    LOGIN_CLIENT_ERROR = 152,

    VERIFY_TOKEN_FAILED = 181,

    CREATE_CHATROOM_FAILED = 201,

    CHATROOM_SERVER_ERROR = 210,

    CHATROOM_JSON_INVALID = 231,

    CHATROOM_CLIENT_ERROR = 251,

    CHATROOM_MEMBER_SERVER_ERROR = 310,

    ROOM_MEMBER_CLIENT_ERROR = 351,

};