//
// Created by lambert on 23-6-2.
//

#pragma once
enum class state_code {
  SUCCESS = 0,

  REGISTRATION_NICKNAME_EXISTS = 101,
  REGISTRATION_EMAIL_EXISTS = 102,
  REGISTRATION_SERVER_ERROR = 110,

  LOGIN_ID_NOT_EXIST = 121,
  LOGIN_USERNAME_NOT_EXIST = 122,
  LOGIN_EMAIL_NOT_EXIST = 123,

  LOGIN_PASSWORD_ERROR = 131,


  REGISTRATION_CLIENT_ERROR = 151,
  LOGIN_CLIENT_ERROR = 152,


  CREATE_CHATROOM_FAILED = 201,

};