//
// Created by lambert on 23-6-2.
//

#pragma once
enum class state_code {
  SUCCESS = 0,

  REGISTRATION_NICKNAME_EXISTS = 101,
  REGISTRATION_EMAIL_EXISTS = 102,
  REGISTRATION_SERVER_ERROR = 110,
  REGISTRATION_CLIENT_ERROR = 141,

  LOGIN_ID_NOT_EXIST = 121,
  LOGIN_USERNAME_NOT_EXIST = 122,
  LOGIN_EMAIL_NOT_EXIST = 123,

  QUERY_USER_NOT_EXIST = 141,

  CREATE_CHATROOM_FAILED = 201,

};